# Generated by Django 4.2.13 on 2024-05-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_event_volunteeers_event_volunteers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='items',
            field=models.TextField(default='{}'),
        ),
    ]
