# Generated by Django 5.0.6 on 2024-06-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Username',
        ),
        migrations.AddField(
            model_name='event',
            name='user_id',
            field=models.IntegerField(default=0, max_length=1000),
        ),
    ]
