# Generated by Django 5.0.6 on 2024-06-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_event_username_event_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Username',
            field=models.CharField(default='Test', max_length=5000),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userType',
            field=models.CharField(default='Volunteer', max_length=200),
        ),
    ]
